arm:
  kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
  # Only using position even with loose orientation constrinats seems to fail,
  # so we need to use position only IK.
  position_only_ik: true
